ALTER TYPE "SpecialRoundMarketKind" ADD VALUE 'TEAM_MOST_SHOTS_ON_GOAL';
ALTER TYPE "SpecialRoundMarketKind" ADD VALUE 'TEAM_MOST_CORNERS';
ALTER TYPE "SpecialRoundMarketKind" ADD VALUE 'TEAM_MOST_CARDS';
ALTER TYPE "SpecialRoundMarketKind" ADD VALUE 'TEAM_MOST_SHOTS';
